### ISSUE TITLE
Internal JSON - RPC Error

### ISSUE THREAD

**Issue by PrintRH** [TreasureProject/magicswap#89]
Hi, I am experiencing Internal JSON - RPC error when trying to swap from MAGIC to ELM. I had a successful swap a few days ago but I am not sure why the transaction fails now. 

Any advice is much appreciated.

![image](https://user-images.githubusercontent.com/93211672/230802395-958eab05-70a7-467e-95e1-08f033ce0e74.png)

**Comment by alecananian** [comment]
Sorry I hadn't seen this earlier. This issue occurs if you don't have the correct amount of a token approved for trading. We fixed this with #88
